---
title: "Homework8"
author: "Angela McMahon"
date: "3/25/2026"
output: 
  html_document:
  code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#remove warnings at END
library(tidyverse)
library(Lock5Data)
library(knitr)
data("StudentSurvey")
```



### Selecting Variables and Creating BMI Column  

```{r}
Survey2 <-StudentSurvey%>% 
  mutate(BMI.r= 701*(Weight/(Height^2)))%>%
  mutate(BMI= round(BMI.r,1))%>%
  select("Sex", "Weight", "Height","BMI")

Survey2%>%
  head(n=6)%>%
  kable()
  
```


### Binning BMI Status 

```{r}
Survey3<-Survey2%>%
  mutate(Health_Status = cut(BMI, c(-Inf, 18.5, 24.9, 29.9, Inf), labels= c("Underweight","Healthy Weight","Overweight","Obsese")))
  
Survey3%>%
  head(n=6)%>%
  kable()
  
```


### Highest and Lowest BMIs for Males and Females 

```{r}
Survey3%>%
  group_by(Sex)%>%
  summarize(Max= max(BMI, na.rm=TRUE), Min= min(BMI, na.rm=TRUE))%>% kable()
```

### New Column: The Greater of Student's Verbal and Math SAT Scores

```{r}
StudentSurvey%>%
  mutate(HSAT=pmax(MathSAT, VerbalSAT, na.rm=TRUE), .keep="used")%>%
  head(n=6)%>%
  kable()
```


### New Column: Z-score for Students Total SAT Scores

```{r}
StudentSurvey%>%
  mutate(Zscore=abs(SAT-mean(SAT))/sd(SAT), .keep="used")%>%
  head(n=6)%>%
  kable()
```

